import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, ParameterGrid
from sklearn.preprocessing import StandardScaler
from data_prepare import generate_pairs

def custom_grid_search(seed_path):
    print(f"----------------------Seed: {seed_path}----------------------")

    # Load data from file generated by data_prepare
    data = np.load(seed_path, allow_pickle=True)
    X_train_raw = data['X_train_raw']
    y_train_authors = data['y_train_authors']
    unique_authors = np.unique(y_train_authors)

    # Search space for hyperparameters
    param_grid = {
        'C': [0.1, 1, 10]
    }

    # 5-fold cross validation (for splitting authors, not articles or pairs)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)

    # Dictionary for storing results
    results = {str(p): {'train': [], 'val': []} for p in ParameterGrid(param_grid)}

    print("\n[GRID SEARCH]")

    # Generate pairs for training and validation
    # train_idx: index of training folds
    # val_ind: index of validation fold
    for fold, (train_idx, val_idx) in enumerate(kf.split(unique_authors)):

        # Authors for training
        cv_train_authors = unique_authors[train_idx]
        # AUthors for validation
        cv_val_authors = unique_authors[val_idx]

        # Generate pairs for training and validation sets
        X_cv_train, y_cv_train = generate_pairs(X_train_raw, y_train_authors, cv_train_authors)
        X_cv_val, y_cv_val = generate_pairs(X_train_raw, y_train_authors, cv_val_authors)

        # Apply standard scale
        scaler = StandardScaler()
        X_cv_train_scaled = scaler.fit_transform(X_cv_train)
        X_cv_val_scaled = scaler.transform(X_cv_val)

        for params in ParameterGrid(param_grid):
            # Training
            model = LogisticRegression(**params, random_state=42, max_iter=1000)
            model.fit(X_cv_train_scaled, y_cv_train)

            train_acc = model.score(X_cv_train_scaled, y_cv_train)
            val_acc = model.score(X_cv_val_scaled, y_cv_val)

            # Store accuracy
            results[str(params)]['train'].append(train_acc)
            results[str(params)]['val'].append(val_acc)
            # print(f"  + Params {params}: Val Acc = {val_acc:.4f}")

    for params_str, scores in results.items():
        val_scores = scores['val']
        mean_train = np.mean(scores['train'])
        mean_val = np.mean(scores['val'])

        fold_details = " | ".join([f"Fold {i+1}: {score:.4f}" for i, score in enumerate(val_scores)])

        print(f" {params_str}")
        print(f"   - Fold Details : [ {fold_details} ]")
        print(f"   - Summary      : Train Mean: {mean_train:.4f}  =>  Val Mean: {mean_val:.4f}\n")
    print("="*60 + "\n")
