import numpy as np
import random
from sklearn.svm import SVC
from sklearn.model_selection import KFold, ParameterGrid
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from data_prepare import generate_pairs

def custom_grid_search(seed_path):

    # Load data from file generated by data_prepare
    print(f"----------------------Seed: {seed_path}----------------------")
    data = np.load(seed_path, allow_pickle=True)
    
    X_train_raw = data['X_train_raw']
    y_train_authors = data['y_train_authors']

    unique_authors = np.unique(y_train_authors)

    # Search space for hyperparameters
    param_grid = {
        'C': [0.1, 1, 10],
        'gamma': [0.001, 0.01, 0.1]
    }

    # 5-fold cross validation (for splitting authors, not articles or pairs)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    
    results = []

    print("\n[GRID SEARCH]")

    for params in ParameterGrid(param_grid):
        print(f"\n{params}")
        
        fold_train_scores, fold_val_scores = [], []
        
        # Generate pairs for training and validation
        # train_idx: index of training folds
        # val_ind: index of validation fold
        for fold, (train_idx, val_idx) in enumerate(kf.split(unique_authors)):
            # Authors for training
            cv_train_authors = unique_authors[train_idx]
            # AUthors for validation
            cv_val_authors = unique_authors[val_idx]
            
            # Generate pairs for training and validation sets
            X_cv_train, y_cv_train = generate_pairs(X_train_raw, y_train_authors, cv_train_authors)
            X_cv_val, y_cv_val = generate_pairs(X_train_raw, y_train_authors, cv_val_authors)
            
            # Apply standard scale
            scaler = StandardScaler()
            X_cv_train_scaled = scaler.fit_transform(X_cv_train)
            X_cv_val_scaled = scaler.transform(X_cv_val)
            
            # Training
            model = SVC(**params, kernel='rbf', random_state=42)
            model.fit(X_cv_train_scaled, y_cv_train)
            
            # Report accuracy
            train_acc = model.score(X_cv_train_scaled, y_cv_train)
            val_acc = model.score(X_cv_val_scaled, y_cv_val)
            
            fold_train_scores.append(train_acc)
            fold_val_scores.append(val_acc)
            print(f"  + Fold {fold + 1}: Val Acc = {val_acc:.4f}")
            
        mean_train = np.mean(fold_train_scores)
        mean_val = np.mean(fold_val_scores)
        print(f"=> {params} | Train Mean: {mean_train:.4f} | Val Mean: {mean_val:.4f}\n\n")