import numpy as np
import time
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from data_prepare import generate_pairs

def run_logistic_regression(seed_path, c=1.0):
    print(f"File: {seed_path} | C = {c}\n")

    # Load data from file generated by data_prepare
    data = np.load(seed_path, allow_pickle=True)
    
    X_train_raw = data['X_train_raw']
    y_train_authors = data['y_train_authors']
    X_test_pairs = data['X_test_pairs']
    y_test_pairs = data['y_test_pairs']

    unique_authors = np.unique(y_train_authors)
    
    # Generate pairs for training
    X_train_full, y_train_full = generate_pairs(X_train_raw, y_train_authors, unique_authors)

    # Standard scale
    scaler = StandardScaler()
    X_train_full_scaled = scaler.fit_transform(X_train_full)
    X_test_pairs_scaled = scaler.transform(X_test_pairs)
    
    # Training
    model = LogisticRegression(C=c, max_iter=1000, random_state=42) 
    model.fit(X_train_full_scaled, y_train_full)
    
    # Predict
    y_pred = model.predict(X_test_pairs_scaled)
    y_pred_proba = model.decision_function(X_test_pairs_scaled)
    
    # Result
    test_acc = model.score(X_test_pairs_scaled, y_test_pairs)
    test_auc = roc_auc_score(y_test_pairs, y_pred_proba)
    
    print("INFORMATION:")
    print(classification_report(y_test_pairs, y_pred, target_names=['Different (0)', 'Same (1)']))
    
    print("Confusion Matrix:")
    print(confusion_matrix(y_test_pairs, y_pred))
    
    print(f"-> Accuracy: {test_acc:.4f}")
    print(f"-> ROC-AUC : {test_auc:.4f}")

    print("-------------------------------------------\n")
