import numpy as np
import pandas as pd
import random
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from data_prepare import generate_pairs

# Traning model with selected hyperparameter

def train_manual_params(seed_path, c, gamma):
    print(f"File: {seed_path} | C={c}, Gamma={gamma}")
    
    # Load data from file generated by data_prepare
    data = np.load(seed_path, allow_pickle=True)
    
    X_train_raw = data['X_train_raw']
    y_train_authors = data['y_train_authors']
    X_test_pairs = data['X_test_pairs']
    y_test_pairs = data['y_test_pairs']

    unique_authors = np.unique(y_train_authors)
    
    # Generate pairs for training
    X_train_full, y_train_full = generate_pairs(X_train_raw, y_train_authors, unique_authors)
    
    print(X_train_full.shape)
    print(X_test_pairs.shape)

    # Standard scale
    final_scaler = StandardScaler()
    X_train_full_scaled = final_scaler.fit_transform(X_train_full)
    X_test_pairs_scaled = final_scaler.transform(X_test_pairs)
    
    # Traninig
    model = SVC(C=c, gamma=gamma, kernel='rbf', random_state=42)
    model.fit(X_train_full_scaled, y_train_full)
    
    # Predict
    y_pred = model.predict(X_test_pairs_scaled)
    y_pred_proba = model.decision_function(X_test_pairs_scaled)
    
    # Report
    test_acc = model.score(X_test_pairs_scaled, y_test_pairs)
    test_auc = roc_auc_score(y_test_pairs, y_pred_proba)
    
    print("INFORMATION:")
    print(classification_report(y_test_pairs, y_pred, target_names=['Different (0)', 'Same (1)']))
    
    print("Confusion Matrix:")
    print(confusion_matrix(y_test_pairs, y_pred))
    
    print(f"-> Accuracy: {test_acc:.4f}")
    print(f"-> ROC-AUC : {test_auc:.4f}")
    
    return test_acc, test_auc

if __name__ == "__main__":
    test_accuracies = []
    test_aucs = []
    
    for i in range(5):
        t = i + 19
        seed_path = f'processed_data_seed_{t}.npz'
        
        random.seed(t)
        np.random.seed(t)

        acc, auc = train_manual_params(seed_path, c=0.1, gamma=0.001)
        
        test_accuracies.append(acc)
        test_aucs.append(auc)
        
    print("\n" + "*"*50)
    print("RESULT")
    print("*"*50)
    print(f"Mean Accuracy: {np.mean(test_accuracies):.4f} ± {np.std(test_accuracies):.4f}")
    print(f"Mean ROC-AUC: {np.mean(test_aucs):.4f} ± {np.std(test_aucs):.4f}")